### ISSUE TITLE
Test steps API throwing TS2339 [ERROR] in GitHub Actions

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#12524]
When running tests in GitHub Actions any tests that are using the new test steps API fail with the following error:
```
 error: TS2339 [ERROR]: Property 'step' does not exist on type 'TestContext'.
```

This is my Deno setup job in the pipeline:
```yaml
  - name: Setup Deno
    uses: denoland/setup-deno@v1.1.0
    with:
      deno-version: v1.x
```

And running tests with:

```
    run: deno test -A --coverage=cov --doc
```

This problem doesn't occur when testing locally on Deno v1.15.2.
