### ISSUE TITLE
`deno compile`/eszip does not follow redirects

### ISSUE THREAD

**Issue by mweichert** [denoland/deno#13704]
Since v1.19.0 was released, we're seeing a problem when running `deno compile` in Github Actions.

See: https://github.com/ecadlabs/taqueria/runs/5234787765?check_suite_focus=true

We were using:
```
- name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "^1.0.0"
```

When I hardcode the version to 1.18.2 everything works fine:

https://github.com/ecadlabs/taqueria/runs/5236615612?check_suite_focus=true
