### ISSUE TITLE
lsp: rework workspace folders

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#14455]
Not all editors / LSP clients support per-project configuration, not all even support *any* configuration. So it becomes non-trivial to make it work with some editors.

For example I've had to figure out a magic incantation to add to [Helix's languages.toml](https://github.com/helix-editor/helix/blob/166818359030cd1649327160c9020d943a8de244/languages.toml):

```toml
config = { deno = { enable = true, lint = true } }
```

by looking at debug messages to see what the server doesn't like.

_Originally posted by @unrelentingtech in https://github.com/denoland/deno/issues/13228#issuecomment-1114361060_

The initial implementation of workspace folders was naïve on my part and in doing the `enableFolders` feature I realised a much cleaner and better way to do it.  We need to rework this feature and respect the client capability around workspace folders, so clients don't have to implement such things.

**Comment by hemedani** [comment]
`helix` support local config. just put this config for deno LSP in `.helix/languages.toml` in the root of the project :
```
﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿[[language]]
name = "javascript"
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
config = { enable = true, lint = true, unstable = true }
language-server = { command = "deno", args = ["lsp"], language-id = "javascript" }

[[language]]
name = "jsx"
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
config = { enable = true, lint = true, unstable = true }
language-server = { command = "deno", args = ["lsp"], language-id = "javascriptreact" }

[[language]]
name = "typescript"
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
config = { enable = true, lint = true, unstable = true }
language-server = { command = "deno", args = ["lsp"], language-id = "typescript" }

[[language]]
name = "tsx"
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
config = { enable = true, lint = true, unstable = true }
language-server = { command = "deno", args = ["lsp"], language-id = "typescriptreact" }
```

**Comment by lino-levan** [comment]
@kitsonk I know you're not part of deno core anymore, but could you give any quick tips / ideas on what you meant by this?
> I realised a much cleaner and better way to do it.

**Comment by nayeemrmn** [comment]
Fixed by #20358.

**Comment by 3210jr** [comment]
@hemedani Your comment saved me a lot of pain before!!! Now with the updates to helix editor (v 23.10) seems like nothing works - I might just not really understand how to get things set up. Suggestions, hover, go to definition, etc not working currently.

Can you please please please share your current helix config for your per project `languages.toml` file? (or just the relevant parts for a deno project)

Thanks again for all the pain you saved me with your previous config!!!

**Comment by hemedani** [comment]
@3210jr It's very simple bro
It is the new `languages.toml` file:
```toml
[[language]]
name = "javascript"
scope = "source.js"
injection-regex = "^(js|javascript)$"
file-types = ["js", "jsx", "mjs"]
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
# comment-token = "//"
# config = { enable = true, lint = true, unstable = true, importMap = "deno.json" }
language-servers = ["deno"]
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "jsx"
scope = "source.jsx"
injection-regex = "jsx"
file-types = ["jsx"]
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
language-servers = ["deno"]
indent = { tab-width = 2, unit = "  " }
grammar = "javascript"
auto-format = true

[[language]]
name = "typescript"
scope = "source.ts"
injection-regex = "^(ts|typescript)$"
file-types = ["ts"]
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
language-servers = ["deno"]
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[language]]
name = "tsx"
scope = "source.tsx"
injection-regex = "^(tsx)$" # |typescript
file-types = ["tsx"]
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
language-servers = ["deno"]
indent = { tab-width = 2, unit = "  " }
auto-format = true

[language-server.deno]
command = "deno"
args = ["lsp"]
config = { enable = true, lint = true, unstable = true, importMap = "deno.json" }
```
