### ISSUE TITLE
deno inspect with docker container - port forwarding

### ISSUE THREAD

**Issue by avalero** [denoland/deno#15424]
I am trying to inspect a deno app that is ran inside a docker container with docker-compose.

docker-compose configuration is as follows:

```
services:
  api_bo:
    image: denoland/deno:debian-1.23.4
    volumes:
      - type: bind
        source: .
        target: /usr/src
    ports:
      - 9229:9229
      - 6005:3000
    command: bash -c "cd /usr/src/packages/api_bo && deno task inspect"
    depends_on:
      - mongo_db
    environment:
      - MONGO_URL=mongodb://mongo_db:27017/academy_db
      - DB_NAME=academy_db
      - PORT=3000
```

deno.json is as follows:

```
{
  "compilerOptions": {
    "allowJs": false,
    "strict": true
  },
  "lint": {
    "files": {
      "include": ["src/"],
      "exclude": ["src/types.ts"]
    },
    "rules": {
      "tags": ["recommended"],
      "include": [
        "ban-untagged-todo",
        "no-explicit-any",
        "no-implicit-any",
        "explicit-function-return-type"
      ],
      "exclude": ["no-debugger", "no-console"]
    }
  },
  "tasks": {
    "start": "deno run -A --watch src/app.ts",
    "inspect": "deno run -A --inspect src/app.ts"
  },
  "importMap": "../../import_map.json"
}
```
Chrome does not detect the running process.

When running out of docker with deno run, it works just fine.

It seems that deno only listens to connections from `0.0.0.0` and thus it cannot be inspected using docker port forwarding.
