### ISSUE TITLE
Rust analyzer fails for Apple silicon

### ISSUE THREAD

**Issue by vedant-pandey** [denoland/deno#19518]
Rust analyzer fails to load on apple silicon with below error
```
  = note: clang: error: invalid linker name in argument '-fuse-ld=lld'
          
error: aborting due to previous error
```

on changing the rustflag value in config.toml to ld(apple's version of lld linker) it works

```toml
[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=ld"]
```

Rustlangs report on this - https://github.com/rust-lang/rust/issues/39915#issuecomment-618726211
