### ISSUE TITLE
ffi: how to free memory of pointer created in rust?

### ISSUE THREAD

**Issue by c-antin** [denoland/deno#19564]
deno version: 1.34.3
OS: Windows 10 64bit

When creating a string in rust via ffi (+nonblocking), it is never freed, hence memory is leaked.
What is the designated way to free up that space after creating the string on deno side?

Cargo.toml
```toml
[package]
name = "ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[lib]
name = "ffi_lib"
crate-type = ["cdylib"]
```

lib.rs
```rust
//cargo build --release --lib

#[no_mangle]
pub extern "C" fn create_string_ffi() -> *const u8 {
    let result = "#".repeat(1_000_000);
    //the following code was created by expanding #[deno_bindgen]
    let length = (result.len() as u32).to_be_bytes();
    let mut v = length.to_vec();
    v.extend_from_slice(result.as_bytes());
    ::std::mem::forget(result);
    let result = v.as_ptr();
    ::std::mem::forget(v);
    result
}

```

ffi.ts
```ts
const dylib = Deno.dlopen(
  "./target/release/ffi_lib.dll",
  {
    create_string_ffi: {
      parameters: [],
      result: "pointer",
      nonblocking: true,
    },
  } as const,
);

function decode(v: Uint8Array): string {
  return new TextDecoder().decode(v);
}

function encode(s: string): Uint8Array {
  return new TextEncoder().encode(s);
}

function readPointer(v: any): Uint8Array {
  const ptr = new Deno.UnsafePointerView(v);
  const lengthBe = new Uint8Array(4);
  const view = new DataView(lengthBe.buffer);
  ptr.copyInto(lengthBe, 0);
  const buf = new Uint8Array(view.getUint32(0));
  ptr.copyInto(buf, 4);
  return buf;
}

export async function create_string() {
  const rawResult = await dylib.symbols.create_string_ffi();
  const result = readPointer(rawResult);
  return decode(result);
}

```

main.ts
```ts
import { create_string } from "./ffi.ts";

//deno run --unstable --allow-ffi --allow-net main.ts

Deno.serve({ hostname: "0.0.0.0", port: 80 }, async (_req) => {
  const str = await create_string();
  return new Response(str);
});

```
