### ISSUE TITLE
Release for deno-aarch64-unknown-linux-gnu for github runners

### ISSUE THREAD

**Issue by Joeri-Abbo** [denoland/deno#19933]
Heey,

We want to use Deno on ARM64 on our linux runner but this runner can not download the denoland version for this arch. 
<img width="1085" alt="image" src="https://github.com/denoland/deno/assets/34270045/201c2b2c-63a5-4c3f-acac-683ab6ed5d51">

Our github workflow is as follows.
```
name: Deno test

on:
  workflow_call:
    inputs:
      deno-version:
        required: true
        type: string
jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ inputs.deno-version }}
      - name: Run tests
        run: deno test -A
```

Is there a way that arm64 for linux can also be build in new releases?
