### ISSUE TITLE
Subresource integrity for modules

### ISSUE THREAD

**Issue by nknapp** [denoland/deno#200]
I don't know if this already came up, but if security is a major concern and referencing modules via http(s) should be possible, then maybe there should be a way to use [subresource integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) to ensure that the downloaded module isn't tampered with.

It could be part of the hash, like 

```
import { test } from "https://unpkg.com/deno_testing@0.0.5/testing.ts#sha384-oqVuAfXRKap7fdgcCY5uykM6+R9GqQ8K/uxy9rx7HNQlGYl1kPzQho1wx4JwY8wC"
```
That would be very explicit, although not compatible to semver ranges.

**Comment by ianp** [comment]
I think that when a resource if first fetched (and cached) it should be checksummed and this should be written to a file (similar to `yarn.lock` or `package-lock.json`). Maybe having a way to specify required/expected checksums ahead of time as well. For example, in `deno.lock`

```yaml
checksums:
  - required:
    - https://unpkg.com/deno_testing@0.0.5: ["sha384", "oqVuAfXRKa..."]
  - computed:
    - https://unpkg.com/foo@1.2.3: ["sha384", "32e66f3809..."]
```
