### ISSUE TITLE
node compat: `npm:arangojs` fails from Deno v1.34.2

### ISSUE THREAD

**Issue by osddeitf** [denoland/deno#20033]
I run into an issue where the HTTP request was sent with `Transfer-Encoding: chunked`.
See: [arangodb/arangodb#19520](https://github.com/arangodb/arangodb/issues/19520#issuecomment-1663424348)

I remember the package `npm:arangojs` worked in the past (around 2 months ago) for me. So I tried to downgrade Deno and found out that the issue disappeared when I use Deno version < v1.34.2.

Here is my reproduction:
```typescript
import arangodb from 'npm:arangojs';

let mydb = new arangodb.Database()
mydb = await mydb.createDatabase('my-test-database-3')

console.log('create collection')
const accounts = mydb.collection('accounts')
if (!(await accounts.exists())) {
  await accounts.create({ })
}

console.log('begin transaction')
const trx = await mydb.beginTransaction([ accounts ])
await trx.step(() => accounts.save({ name: 'whatever' }))
await trx.commit()
```
Quick setup a arangodb instance with `docker-compose.yml`:
```yaml
services:
  arangodb:
    image: arangodb/arangodb:3.11.2
    # container_name: arangodb
    command:
    - --rocksdb.limit-open-files-at-startup
    # - --database.auto-upgrade
    environment:
      - ARANGO_NO_AUTH=1
      - ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY=600m
    ports:
      - 8529:8529
    # volumes:
    #   - ./data:/var/lib/arangodb3
```
