### ISSUE TITLE
Add example for excluding vendored dependency from `deno coverage`

### ISSUE THREAD

**Issue by KyleJune** [denoland/deno#20521]
The manual page for testing coverage mentioned that there are default inclusions/exclusions and that if you add either of those flags it would override those defaults. However it doesn't show examples of how you can extend it to exclude directories or files.

https://deno.land/manual@v1.25.4/testing/coverage

I tried updating my coverage command to keep the default exclusion but also exclude my vendor and public directories but it doesn't appear to work.

```sh
deno coverage --exclude="(test\.(ts|tsx|mts|js|mjs|jsx|cjs|cts)|^vendor/.*)" --lcov cov > cov.lcov
```

When I use the codecov action to try uploading the cov.lcov, it ends up still having coverage information for my vendor directory. My dependencies are a lot larger than my actual project, so it completely throws off the overall code coverage percentage for my project.

I tried updating my codecov.yml to exclude it but that didn't work. I based it on oak's codecov.yml file then updated the ignore based on the codecov ignoring paths documentation.

https://docs.codecov.com/docs/ignoring-paths

```yml
comment: false
codecov:
  require_ci_to_pass: true
coverage:
  status:
    project:
      default:
        informational: true
ignore:
  - "vendor/**/*"
```
