### ISSUE TITLE
maybe switch node process.kill to use rust

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#23056]
This currently shell out to call `kill`, this makes any program that uses this require the run permission. Implementing this in rust would make it not require this permission.

Program that uses this:

- vscode extracted language servers

```toml
command = "deno"
args = ["run",  "--allow-read", "--allow-env", "--allow-run=kill", "npm:vscode-langservers-extracted@4.8.0/vscode-css-language-server",  "--stdio"]
```

https://github.com/denoland/deno/blob/ec9342f95a950ac13f57c85ef577e3bbab180e1a/ext/node/polyfills/process.ts#L266
