### ISSUE TITLE
fmt does not preserve CSS property casing

### ISSUE THREAD

**Issue by lts20050703** [denoland/deno#26420]
**Input:**
```css
@plugin "daisyui/theme" {
	name: "dark";
	prefersDark: true;
}
```

**Output:**
```css
@plugin "daisyui/theme" {
  name: "dark";
  prefersdark: true;
}

```

**Expected output:**

```css
@plugin "daisyui/theme" {
	name: "dark";
	prefersDark: true;
}

```

**Why?**

The upcoming version of DaisyUI (v5) now involve writing configurations in the CSS file. Some property is in camelCase and the casing needs to be preserved, otherwise it wouldn't work.
