### ISSUE TITLE
JsRuntime initialization fails when integrating deno_url extension

### ISSUE THREAD

**Issue by insuns** [denoland/deno#27413]
I'm encountering an issue when integrating the deno_url extension into deno_core within a test project. Despite trying various approaches, I consistently receive the following error during JsRuntime initialization:
```txt
 Failed to initialize a JsRuntime: Following modules were not evaluated; make sure they are imported from other code: 
    - ext:deno_console/01_console.js 
   - ext:deno_url/00_url.js 
   - ext:deno_webidl/00_webidl.js 
   - ext:deno_url/01_urlpattern.js 
```

Cargo.toml:
```toml
[package]
name    = "deno_url_test"
version = "0.1.0"
edition = "2021"

[dependencies]
v8          = { version = "130.0.1", default-features = false }
deno_core   = { version = "0.326.0", default-features = false }
deno_url    = "0.183.0"
deno_webidl = "0.183.0"
deno_console = "0.183.0"
tokio       = { version = "1.35.1", features = ["full"] }
anyhow      = "1.0.75"
```

rust code：
```rust
use deno_core::error::AnyError;
use deno_core::{extension, op2, OpState};
use deno_core::{JsRuntime, RuntimeOptions};

#[op2]
#[string]
fn op_test() -> Result<String, AnyError> {
    Ok("Hello from Rust!".to_string())
}

extension! {
    TestExtension,
    ops = [op_test],
    state = |state: &mut OpState| {
        ()
    }
}

#[tokio::main]
async fn main() -> Result<(), AnyError> {
    let mut runtime = JsRuntime::new(RuntimeOptions {
        extensions: vec![
            TestExtension::init_ops(),
            deno_console::deno_console::init_ops_and_esm(),
            deno_webidl::deno_webidl::init_ops_and_esm(),
            deno_url::deno_url::init_ops_and_esm(),
        ],
        ..Default::default()
    });

    let code = r#"
import "ext:deno_webidl/00_webidl.js"; 
import "ext:deno_console/01_console.js"; 
import "ext:deno_url/00_url.js"; 
import "ext:deno_url/01_urlpattern.js";

Object.defineProperty(globalThis, "URL", {
  value: url.URL,
  enumerable: false,
  configurable: true,
  writable: true,
});

Object.defineProperty(globalThis, "URLPattern", {
  value: url.URLPattern,
  enumerable: false,
  configurable: true,
  writable: true,
});

Object.defineProperty(globalThis, "URLSearchParams", {
  value: url.URLSearchParams,
  enumerable: false,
  configurable: true,
  writable: true,
});

        const result = Deno.core.ops.op_test();
        console.log('Custom op result:', result);
    "#;

    runtime.execute_script("[test]", code).map_err(|e| {
        println!("Script execution error: {:?}", e);
        e
    })?;

    Ok(())
}

```
