### ISSUE TITLE
bug: Failed to initialize a JsRuntime - Uncaught SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by codekeyz** [denoland/deno#27868]
Version: Deno x.x.x

I have this rust code that just fails when i try to run it. I only needed `deno_fetch` but seems i have to pull these other dependencies.

Sadly, i can't get past `deno_telemtry`.

```rust
  let extensions = vec![
        deno_telemetry::deno_telemetry::init_ops_and_esm(),
        deno_webidl::deno_webidl::init_ops_and_esm(),
        deno_console::deno_console::init_ops_and_esm(),
        deno_url::deno_url::init_ops_and_esm(),
        deno_web::deno_web::init_ops_and_esm::<PermissionsContainer>(
            Default::default(),
            Default::default(),
        ),
        deno_net::deno_net::init_ops_and_esm::<PermissionsContainer>(None, None),
        deno_fetch::deno_fetch::init_ops_and_esm::<PermissionsContainer>(Default::default()),
    ];

    let mut runtime = JsRuntime::new(RuntimeOptions {
        module_loader: Some(Rc::new(FsModuleLoader)),
        import_assertions_support: deno_core::ImportAssertionsSupport::Error,
        startup_snapshot: None,
        inspector: false,
        extensions,
        ..Default::default()
    });
```

It fails with the error below.

```
    Blocking waiting for file lock on build directory
   Compiling dart_v8_runtime v0.1.0 (/Users/codekeyz/Projects/OpenSource/dart_v8_runtime)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 3.26s
thread '<unnamed>' panicked at /Users/codekeyz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.331.0/runtime/jsruntime.rs:740:9:
Failed to initialize a JsRuntime: Uncaught SyntaxError: Unexpected reserved word
    at ext:deno_telemetry/telemetry.ts:54:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x158628998 - std::backtrace_rs::backtrace::libunwind::trace::h6285d60e8a2c022a
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:        0x158628998 - std::backtrace_rs::backtrace::trace_unsynchronized::h21fc036d4b8dd7fe
                               at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x158628998 - std::sys::backtrace::_print_fmt::h69654d1f9cd065f2
```

Package versions

```toml
[dependencies]
deno_fetch = "=0.211.0"
deno_permissions = "0.46.0"
deno_core = "0.331.0"
deno_console = "0.187.0"
deno_telemetry = "0.9.0"
deno_webidl = "0.187.0"
deno_url = "0.187.0"
deno_web = "0.218.0"
deno_http = "0.185.0"
deno_net = "0.179.0"
deno_websocket = "0.192.0"
```
