### ISSUE TITLE
deno_http can not provide custom property extractor

### ISSUE THREAD

**Issue by vanppo** [denoland/deno#28420]
After https://github.com/denoland/deno/pull/28317, it is not possible to provide custom property extractor for deno_http.

This probably due to the [Feature unification](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification) of cargo, so my `default-features = false` does not work as expected.

```toml
# Cargo.toml
[package]
name = "runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
deno_http = { version = "0.192.0", default-features = false }
deno_runtime = { version = "0.202.0", features = ["transpile"] }
```

```plain
$ cargo tree -f "{p} {f}"
runtime v0.1.0 (/Users/vanppo/Downloads/runtime) 
├── deno_http v0.192.0 default,default_property_extractor
└── deno_runtime v0.202.0 deno_ast,transpile
    └── deno_http v0.192.0 default,default_property_extractor (*)
```
