### ISSUE TITLE
Idea: Deno Workspace

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno#4275]
## Rationale

* We want a way to easily manage dependencies:
  * We want `import` lines to be shorter, so we need import-map, but we don't want to write them by hand.
  * We want to easily update our dependency versions without manually search-and-replace.
* We want to easily grant permissions to scripts:
  * `--allow-all` is convenient, but risky.
  * `--allow-foo --allow-bar --allow-baz ...` is long and hard to type.

## Suggestion

* Implement a `deno-workspace` file that Deno automatically loads if it exists in current working directory.
* This `deno-workspace` file...
  * ...is NOT equivalent to NPM's `package.json`: Unlike `package.json`, `deno-workspace` file won't be published to registry, and even if it does, Deno will not load it.
  * ...is equivalent to `tsconfig.json`, `pnpm-workspace.yaml`, `stack.yaml`, `Makefile` and other build file formats: Deno and other tools may use it to build binaries.

## Requirements

* There is only one `deno-workspace` file per workspace.
* `deno-workspace` files of dependencies (should there be any) are completely ignored.
* There is only one file name and one format for `deno-workspace` file.
  * It might be tempting to support multiple formats, but that would only introduce complexity.
* Filename:
  * Basename should be `deno-workspace`.
  * Extension can be discuss later.
* If a standard [registry API](https://github.com/denoland/deno/issues/4244) is specified, Deno Workspace should support it out-of-the-box.

## Example CLI Commands

```sh
# Generate `deno-workspace` file
deno init

# Generate import map and lock file
deno gen-import-map

# Without arguments, `deno fetch` should look for `deno-workspace` file
deno fetch

# Loads `deno-workspace` configuration for REPL session
deno repl

# If LOCAL_FILE belongs to current working directory (directly or indirectly), Deno should load workspace file before executing the script
deno run LOCAL_FILE

# Generate import map, resolve all import URLs so that library consumer won't reply on our import map, and compile to JavaScript
deno make

# Update all dependencies to latest versions.
deno outdated --update
```

## Example `deno-workspace` file

```yaml
# I write this in YAML because it is easier to type. Deno Workspace File's format and name need to be discussed further.
registries:
  std: https://deno.land/std/{pkgname}@{pkgver}/mod.ts
  x: https://deno.land/x/{pkgname}@{pkgver} # BTW, how do I specify versions of third party libraries?
  private: https://mycompany/deno/{pkgname}/{pkgver}/index.js
permissions:
  '**/*.ts':
    read:
      - '{workspace-root}/**/*.txt'
    write:
      - '{script-dirname}/{script-basename}.log'
  '@std/server': # This syntax is similar to NPM namespaces
    net: true
license: MIT
```

### JSON

* **Pros:**
  * Native support
* **Cons:**
  * Hard and slow to type
  * No comments
  * No multi-line string
  * No trailing comma → Does not work well with `git diff` and `git merge`
  * Property keys must be quoted
  * Only support JSON types. JavaScript such as Map and Set are not supported.

### JSON5

* **Pros:**
  * Parsers are available: [npm/json5](https://www.npmjs.com/package/json5), [crates/json5](https://crates.io/crates/json5).
  * Support comments.
  * Support trailing comma.
  * Support unquoted property keys.
* **Cons:**
  * No multi-line strings.
  * Only support JSON types. JavaScript types such as Date, Map and Set are not supported.

### TOML

* **Pros:**
  * Parsers are available: [npm/toml](https://www.npmjs.com/package/toml), [crates/toml](https://crates.io/crates/toml).
  * Re-implementation (if need-be) is relatively easy.
  * Support comments.
  * No needs for comma, no needs for trailing comma.
  * Support multi-line strings.
  * Support additional JavaScript types: Date.
* **Cons:**
  * Indentation of multi-line strings are preserved as-is. No stripping of indentation.
  * Poor support for nested objects.
  * Map and Set are not supported.

### RON (https://github.com/ron-rs/ron)

* **Pros:**
  * Rust parser is available. It can be compiled to WASM.
  * Support comments.
  * Support trailing comma.
  * Support multi-line strings.
  * Can support any JavaScript type.
  * Clear semantic: User is required to write constructor name.
* **Cons:**
  * Indentation of multi-line strings are preserved as-is. No stripping of indentation.
  * No native JavaScript parser. It must be compiled to WASM.

### YAML

* **Pros:**
  * Parsers are available: [npm/js-yaml](https://www.npmjs.com/package/js-yaml), [npm/yaml](https://www.npmjs.com/package/yaml), [crates/yaml](https://crates.io/crates/yaml).
  * Support comments.
  * No need for trailing comma.
  * Support multi-line strings.
  * Strip extraneous indentation of a multi-line string.
  * Can support any JavaScript type.
* **Cons:**
  * Big specification. Expect inconsistent result between different parsers.
  * Some people dislike significant whitespaces (not me).

### Programmable JavaScript/TypeScript

* **Pros:**
  * Native support.
  * Extremely flexible.
  * Support multi-line strings.
  * Can support any JavaScript type.
* **Cons:**
  * External tools can only read, not write. User must edit the file manually.
  * Multi-line strings are preserved as-is. User must use complicated technique to strip indentation.

### My Preference

* I prefer YAML the most, RON second, JSON5 third, and then TOML.
* I'm against using JSON file and JavaScript file.
