### ISSUE TITLE
How can I tell other developers about the executables I use in the project?

### ISSUE THREAD

**Issue by CeamKrier** [denoland/deno#5421]
Let's say I'm using a few deno executables while developing the project. Since the downloaded executables information **does not register** (like devDependencies in package.json) anywhere in the project by default (as far as I know) how should I transmit that information for other fellow developers to not struggle while picking the **right** executable?

For example, I can use a script runner's `.yaml` file to define devDeps that I use inside the project. 
```
scripts:
  start: deno run --allow-net --allow-read index.ts
  clean: deno run --allow-net --allow-read --reload index.ts
  devDeps:
    - deno install --allow-read --allow-env --allow-run -n vr https://deno.land/x/velociraptor/cli.ts
```

But that poses another problem. You would need to have the ``script runner` executable to run that command. So some sort of vicious situation arises.

And it might be fairly easy to spot the file that guides you what should you install but depending on the size of the project and not having a convention to transfer that information (again, as far as I know) it might become a hassle to spot it.
