### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by chovy** [denoland/deno#6245]
Not sure why this error happens in Docker, it works fine w/o docker.

```
theultimateprepper-api | error: TS2551 [ERROR]: Property 'osName' does not exist on type 'typeof Deno'. Did you mean 'hostname'?
theultimateprepper-api |   return Deno.osName();
theultimateprepper-api |               ~~~~
theultimateprepper-api |     at https://deno.land/std/node/os.ts:195:15
theultimateprepper-api | 
theultimateprepper-api |     'hostname' is declared here.
theultimateprepper-api |       export function hostname(): string;
theultimateprepper-api |                       ~~~~~~
theultimateprepper-api |         at $asset$/lib.deno.unstable.d.ts:1184:19
```

Dockerfile:

```
FROM hayd/alpine-deno:1.0.0

EXPOSE 5000
WORKDIR /app
USER deno
ADD . /app
#RUN deno cache app.ts
CMD ["run", "--allow-env",  "--allow-net", "--allow-write", "--allow-read", "--allow-plugin", "--unstable", "app.ts"] 
```

docker-compose.yml:

```
version: '3'

services:
  api:
    restart: always
    build: .
    container_name: theultimateprepper-api
    ports:
      - "127.0.0.1:8000:8000"
```
